DROP DATABASE IF EXISTS billboard;
CREATE DATABASE billboard;
\c billboard;

DROP TABLE IF EXISTS favorites;

CREATE TABLE favorites (
  favorite_id integer GENERATED BY DEFAULT AS IDENTITY,
  song_id varchar(50) NOT NULL
) WITH (
  OIDS=FALSE
);